name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print environment variables
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}"
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}"
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}"
          echo "DATABASE_DRIVER_CLASS_NAME=${{ secrets.DATABASE_DRIVER_CLASS_NAME }}"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Cache Maven packages
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-

#      - name: Build with Maven
#        env:
#          DATABASE_URL: ${{ secrets.DATABASE_URL }}
#          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
#          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
#          DATABASE_DRIVER_CLASS_NAME: ${{ secrets.DATABASE_DRIVER_CLASS_NAME }}
#        run: mvn clean install -X

      - name: Run tests
        run: mvn test

      - name: Verify application runs
        run: mvn spring-boot:run -Dspring-boot.run.arguments=--server.port=8080 &
        shell: bash
