name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Add PostgreSQL dependency for testing
        run: |
          echo '<dependency>' >> pom.xml
          echo '  <groupId>org.postgresql</groupId>' >> pom.xml
          echo '  <artifactId>postgresql</artifactId>' >> pom.xml
          echo '  <scope>test</scope>' >> pom.xml
          echo '</dependency>' >> pom.xml

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Verify application runs (optional step)
        run: mvn spring-boot:run -Dspring-boot.run.arguments=--server.port=8080 &
