name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Add PostgreSQL dependency
        run: |
          sed -i '/<\/dependencies>/ i\
            <dependency>\n\
              <groupId>org.postgresql</groupId>\n\
              <artifactId>postgresql</artifactId>\n\
              <scope>test</scope>\n\
            </dependency>' pom.xml
        shell: bash

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils
        shell: bash

      - name: Validate POM file
        run: xmllint --noout pom.xml
        shell: bash

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Verify application runs (optional step)
        run: mvn spring-boot:run -Dspring-boot.run.arguments=--server.port=8080 &
        shell: bash