name: Spring Boot CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
        - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: mvn clean install -d

      - name: Output environment variables
        run: |
          echo "ENV=$ENV"
          echo "DATABASE_URL=$DATABASE_URL"
          echo "DATABASE_USERNAME=$DATABASE_USERNAME"
          echo "DATABASE_PASSWORD=$DATABASE_PASSWORD"
          echo "DATABASE_DRIVER_CLASS_NAME=$DATABASE_DRIVER_CLASS_NAME"
          echo "MAIL_SERVICE_HOST=$MAIL_SERVICE_HOST"
          echo "MAIL_SERVICE_PORT=$MAIL_SERVICE_PORT"
          echo "MAIL_SERVICE_USERNAME=$MAIL_SERVICE_USERNAME"
          echo "MAIL_SERVICE_PASSWORD=$MAIL_SERVICE_PASSWORD"
          echo "MAIL_SERVICE_SMTP=$MAIL_SERVICE_SMTP"
          echo "MAIL_SERVICE_STARTTLS=$MAIL_SERVICE_STARTTLS"
          echo "MAIL_SERVICE_DOMAIN_NAME=$MAIL_SERVICE_DOMAIN_NAME"


      - name: Run Spring Boot Application
        run: mvn spring-boot:run
        env:
          ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_DRIVER_CLASS_NAME: ${{ secrets.DATABASE_DRIVER_CLASS_NAME }}

          MAIL_SERVICE_HOST: ${{ secrets.MAIL_SERVICE_HOST }}
          MAIL_SERVICE_PORT: ${{ secrets.MAIL_SERVICE_PORT }}
          MAIL_SERVICE_USERNAME: ${{ secrets.MAIL_SERVICE_USERNAME }}
          MAIL_SERVICE_PASSWORD: ${{ secrets.MAIL_SERVICE_PASSWORD }}
          MAIL_SERVICE_SMTP: ${{ secrets.MAIL_SERVICE_SMTP }}
          MAIL_SERVICE_STARTTLS: ${{ secrets.MAIL_SERVICE_STARTTLS }}
          MAIL_SERVICE_DOMAIN_NAME: ${{ secrets.MAIL_SERVICE_DOMAIN_NAME }}

      - name: Run Tests
        run: mvn test
