name: Spring Boot CI Pipeline

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'  # Run on all PRs to any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: mvn clean install

      - name: Run Spring Boot Application
        run: mvn spring-boot:run
        env:
          ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_DRIVER_CLASS_NAME: ${{ secrets.DATABASE_DRIVER_CLASS_NAME }}

      - name: Run Tests
        run: mvn test
